// puns.mjs — trocadilhos/piadas de dev (PT-BR). Arquivo separado de proposito: e o
// mais fácil de editar e o que mais cresce. Copiado junto do engine no `moodline init`.
// Regras: curto (<= 60 chars, a barra trunca), PT-BR, com twist no final — piada sem
// virada e so uma frase triste.
export const PUNS = [
  // --- git & code review ---
  String.raw`funciona na minha máquina ¯\_(ツ)_/¯`,
  'merge sem conflito é merge mentiroso',
  'prod de pé? reza o commit',
  'rebase com fé, push com medo',
  'git blame aponta pra mim de novo',
  'commit -m "ajustes"',
  'commit gigante, mensagem "wip"',
  'force push, força e fé',
  'git stash: o porão da bagunça',
  'branch final-v2-agora-vai-2',
  'detached HEAD: eu no trabalho',
  'PR pequeno: guerra. PR gigante: LGTM.',
  'PR de 3 mil linhas, boa sorte',
  'aprovado sem ler, clássico',
  'git bisect: perícia forense do meu passado',
  'commit às 18h: descubro amanhã se fui herói',
  // --- deploy & produção ---
  'deploy na sexta, coragem de sobra',
  'deploy "agora vai": não foi',
  'prod é o melhor ambiente de testes',
  'works on prod, falha no demo',
  'rollback é o novo deploy',
  'rollback: ctrl+z de gente grande',
  'rollback às 3 da manhã',
  'sexta 17h: não mexe que tá funcionando',
  'sexta-feira: modo read-only',
  'segunda-feira: rollback do fim de semana',
  'CI verde, prod vermelho, eu roxo',
  'uptime 99,9%: o 0,1% foi hoje',
  'canary release: o canário morreu',
  'hotfix vira feature permanente',
  'homolog e prod: gêmeas que não se falam',
  'deletei o código morto. era o de produção.',
  // --- bugs & debug ---
  'bug? feature não documentada',
  '404: piada não encontrada',
  'tava funcionando ontem',
  'funcionou de primeira? desconfie',
  'é só um if, o que pode dar errado?',
  'o bug é o teste passando errado',
  'off by one, off by sanidade',
  'race condition: quem chega primeiro mente',
  'aumentei o log, o bug ficou tímido',
  'meu bug favorito virou feature paga',
  'console.log até em produção',
  'grep no log: arqueologia digital',
  'segfault: o silêncio constrangedor',
  'expliquei pro pato de borracha. ele pediu demissão.',
  'o pato de borracha já sabe demais',
  'null: o erro de um bilhão de dólares',
  'undefined is not a function (a vida também não)',
  '[object Object]: meu usuário favorito',
  'NaN é número. o JS decidiu, aceita.',
  'sou promise: prometo e fico pendente',
  'esqueci o await: prometi e não esperei',
  'try/catch: tentei, me pegaram',
  'catch vazio: fingindo que não vi',
  '500: o servidor também não sabe',
  'HTTP 418: sou um bule, eu entendo',
  'timeout: até o servidor desistiu de mim',
  'sempre foi DNS. sempre será DNS.',
  'meu type é any, meu futuro é undefined',
  // --- código & arquitetura ---
  'CSS: Continua Sem Solução',
  'recursão: ver "recursão"',
  'TODO: escrever um TODO melhor',
  'semicolon ; o herói anônimo',
  'tabs vs spaces: a guerra eterna',
  'documentação? o código é a doc',
  'legacy: código com medo de mexer',
  'legado roda desde 2009. ninguém sabe por quê.',
  'código legado: eu de seis meses atrás',
  'quem entendia esse módulo saiu em 2021',
  'wiki interna: atualizada em 2019',
  '"depois eu refatoro" — ninguém, nunca',
  'refatorar: mexer no que funcionava',
  'reescrever do zero: a esperança que mata',
  'temporário é o que mais dura',
  'MVP: o provisório definitivo',
  'gambiarra provisória desde 2017',
  'não é gambiarra, é solução orientada a prazo',
  'clean code: li o livro, sujei o repo',
  'SOLID: sólido só o deadline',
  'singleton: padrão de projeto e de vida',
  'hexagonal: o único hexa que temos',
  'microserviço: monólito distribuído',
  'monorepo: tudo junto e misturado',
  'regex: agora você tem 2 problemas',
  'YAML: os espaços te odeiam',
  'timezone: o vilão silencioso',
  'encoding ok até prod: "OlÃ¡, usuÃ¡rio"',
  'z-index: 999999 e fé',
  '!important: o CSS implorando',
  'centralizei a div. aceito aplausos.',
  'mexi no CSS, quebrou o backend',
  'meu código é tão limpo que ninguém entende',
  'virei sênior: agora erro com confiança',
  // --- testes & qualidade ---
  'compilou? então tá pronto',
  'quem precisa de QA tem usuário',
  'mockei tudo: testei nada',
  'meu código passou no teste. o teste era ruim.',
  'cobertura 100%, confiança 0',
  // --- dados & infra ---
  'se eu quisesse fazer consulta tinha virado médico',
  'UPDATE sem WHERE: cardio grátis pro DBA',
  'index errado, query de joelhos',
  'normaliza tabela, desnormaliza a sanidade',
  'JOIN demais, paciência de menos',
  'ORM: SQL com medo de compromisso',
  'NoSQL: schema opcional, arrependimento não',
  'backup? a gente tinha um',
  'cache: o problema e a solução',
  'docker: roda na minha e na sua máquina',
  'container morreu como viveu: sem logs',
  'serverless: o servidor dos outros',
  'fatura da nuvem: jump scare mensal',
  'multicloud: três boletos',
  'otimizei custos: desliguei o ambiente errado',
  'infra as code: o erro agora é versionado',
  'observabilidade: ver o incêndio em 4K',
  'env var faltando, sempre uma',
  'node_modules pesa mais que minha consciência',
  'npm install: baixando a internet',
  'semver: quebra tudo no patch mesmo assim',
  'criptografia caseira: base64 e coragem',
  'commitei o .env — currículo atualizado',
  'autenticação de dois fatores: senha e reza',
  // --- processo & agile ---
  'reunião que podia ser e-mail, de novo',
  'kanban: arrastar é progresso',
  'sprint: corrida sem linha de chegada',
  'retro: reclamar com método',
  'agile: caos com cerimônia',
  'standup virou sentadown de 40min',
  'story point: unidade de medo',
  'burndown: só o time queimou',
  'backlog: cemitério de boas ideias',
  'estimativa: chute com gravata',
  'estimei 2h, já faz 3 dias',
  'escopo: a única coisa que escala sozinha',
  'prazo veio antes do requisito',
  'deadline: substantivo coletivo de pânico',
  'deadline definida por quem não coda',
  'feature flag: o if que virou produto',
  'pair programming: dois pra culpar',
  'post-mortem: culpar o processo educadamente',
  'wontfix: dor arquivada com carinho',
  'issue de 2019, milestone: esperança',
  'sev1: o café acabou',
  'sprint infinita, energia finita',
  'velocity sobe, sanidade desce',
  // --- vida de dev (ácidos) ---
  'sênior é júnior que não dormiu',
  'salário não acompanha o cortisol',
  'on-call: dormir é opcional',
  'alerta às 3h: o servidor sente saudade',
  'burnout com plano de carreira',
  'legado: emprego garantido, alma não',
  'PO sonha, dev acorda às 4h',
  'promovido a fazer mais com menos',
  'pizza não paga hora extra',
  'feedback sandwich, recheio de PIP',
  'culpa do dev, mérito da gestão',
  'todo mundo é fullstack até dar ruim',
  'café é o único stack confiável',
  'startup: equity hoje, boleto também',
  'senioridade é saber dizer "depende"',
  'erro 500: culpa do estagiário',
  'já tentou desligar e ligar a carreira?',
  'Stack Overflow, meu copiloto de verdade',
  'dark mode pra esconder os bugs',
  // --- era da IA ---
  'a IA alucinou uma lib. eu instalei.',
  'IA sugere, git blame me acusa',
  'a IA errou igual eu, só que mais rápido',
  'a IA pediu desculpa e errou de novo. igual eu.',
  'prompt: "conserta". IA: "não".',
  'vibe coding: a vibe era ansiedade',
];
