// puns.mjs — trocadilhos/piadas de dev (PT-BR). Arquivo separado de proposito: e o
// mais fácil de editar e o que mais cresce. Copiado junto do engine no `moodline init`.
// Regras: curto (a barra trunca), PT-BR, sem quebrar em terminal estreito.
export const PUNS = [
  'git push? mais pra git shove',
  'funciona na minha máquina ¯\\_(ツ)_/¯',
  'bug? feature não documentada',
  'merge sem conflito é merge mentiroso',
  'CSS: Continua Sem Solução',
  '404: piada não encontrada',
  'deploy na sexta, coragem de sobra',
  'cache: o problema e a solução',
  'recursão: ver "recursão"',
  'prod de pé? reza o commit',
  'TODO: escrever um TODO melhor',
  'semicolon ; o herói anônimo',
  'rebase com fé, push com medo',
  'git blame aponta pra mim de novo',
  'tabs vs spaces: a guerra eterna',
  'commit -m "ajustes"',
  'tava funcionando ontem',
  'dark mode pra esconder os bugs',
  'café.exe parou de responder',
  'compilou? então tá pronto',
  'é só um if, o que pode dar errado?',
  'prod é o melhor ambiente de testes',
  'documentação? o código é a doc',
  'Stack Overflow, meu copiloto de verdade',
  'um teste a menos, um deploy a mais',
  'null: o erro de um bilhão de dólares',
  'regex: agora você tem 2 problemas',
  'quem precisa de QA tem usuário',
  'funcionou de primeira? desconfie',
  'legacy: código com medo de mexer',
  'hotfix vira feature permanente',
  '"depois eu refatoro" — ninguém, nunca',
  'force push, força e fé',
  'erro 500: culpa do estagiário',
  'clean code? clean café primeiro',
  'deadline: substantivo coletivo de pânico',
  'rollback é o novo deploy',
  'off by one, off by sanidade',
  'YAML: os espaços te odeiam',
  'docker: roda na minha e na sua máquina',
  'o bug é o teste passando errado',
  'sexta 17h: não mexe que tá funcionando',
  'pair programming: dois pra culpar',
  'microserviço: monólito distribuído',
  'temporário é o que mais dura',
];
