// puns.mjs — trocadilhos/piadas de dev (PT-BR). Arquivo separado de proposito: e o
// mais fácil de editar e o que mais cresce. Copiado junto do engine no `moodline init`.
// Regras: curto (a barra trunca), PT-BR, sem quebrar em terminal estreito.
export const PUNS = [
  'git push? mais pra git shove',
  String.raw`funciona na minha máquina ¯\_(ツ)_/¯`,
  'bug? feature não documentada',
  'merge sem conflito é merge mentiroso',
  'CSS: Continua Sem Solução',
  '404: piada não encontrada',
  'deploy na sexta, coragem de sobra',
  'cache: o problema e a solução',
  'recursão: ver "recursão"',
  'prod de pé? reza o commit',
  'TODO: escrever um TODO melhor',
  'semicolon ; o herói anônimo',
  'rebase com fé, push com medo',
  'git blame aponta pra mim de novo',
  'tabs vs spaces: a guerra eterna',
  'commit -m "ajustes"',
  'tava funcionando ontem',
  'dark mode pra esconder os bugs',
  'café.exe parou de responder',
  'compilou? então tá pronto',
  'é só um if, o que pode dar errado?',
  'prod é o melhor ambiente de testes',
  'documentação? o código é a doc',
  'Stack Overflow, meu copiloto de verdade',
  'um teste a menos, um deploy a mais',
  'null: o erro de um bilhão de dólares',
  'regex: agora você tem 2 problemas',
  'quem precisa de QA tem usuário',
  'funcionou de primeira? desconfie',
  'legacy: código com medo de mexer',
  'hotfix vira feature permanente',
  '"depois eu refatoro" — ninguém, nunca',
  'force push, força e fé',
  'erro 500: culpa do estagiário',
  'clean code? clean café primeiro',
  'deadline: substantivo coletivo de pânico',
  'rollback é o novo deploy',
  'off by one, off by sanidade',
  'YAML: os espaços te odeiam',
  'docker: roda na minha e na sua máquina',
  'o bug é o teste passando errado',
  'sexta 17h: não mexe que tá funcionando',
  'pair programming: dois pra culpar',
  'microserviço: monólito distribuído',
  'temporário é o que mais dura',
  'se eu quisesse fazer consulta tinha virado médico',
  'undefined is not a function (a vida também não)',
  'segfault: o silêncio constrangedor',
  'works on prod, falha no demo',
  'CI vermelho, café preto',
  'kanban: arrastar é progresso',
  'sprint: corrida sem linha de chegada',
  'code freeze, coração quente',
  'git stash: o porão da bagunça',
  'feature flag: o if que virou produto',
  'monorepo: tudo junto e misturado',
  'lint reclamando, eu também',
  'retro: reclamar com método',
  'env var faltando, sempre uma',
  'timezone: o vilão silencioso',
  'UTF-8 ou nada faz sentido',
  'backup? a gente tinha um',
  'race condition: quem chega primeiro mente',
  'memory leak: a água some sozinha',
  'um await esquecido arruína tudo',
  'console.log até em produção',
  'PR de 3 mil linhas, boa sorte',
  'aprovado sem ler, clássico',
  'commit gigante, mensagem "wip"',
  'rollback às 3 da manhã',
  'index errado, query de joelhos',
  'normaliza tabela, desnormaliza a sanidade',
  'JOIN demais, paciência de menos',
  // --- ácidos: vida de programador ---
  'sênior é júnior que não dormiu',
  'salário não acompanha o cortisol',
  'reunião que podia ser e-mail, de novo',
  'on-call: dormir é opcional',
  'burnout com plano de carreira',
  'estimei 2h, já faz 3 dias',
  'legado: emprego garantido, alma não',
  'PO sonha, dev acorda às 4h',
  'agile: caos com cerimônia',
  'promovido a fazer mais com menos',
  'pizza não paga hora extra',
  'home office: a casa virou o trabalho',
  'feedback sandwich, recheio de PIP',
  'meu código é tão limpo que ninguém entende',
  'deadline definida por quem não coda',
  'reescrever do zero: a esperança que mata',
  'velocity sobe, sanidade desce',
  'culpa do dev, mérito da gestão',
  'todo mundo é fullstack até dar ruim',
  'café é o único stack confiável',
  'startup: equity hoje, boleto também',
  'senioridade é saber dizer "depende"',
  'sprint infinita, energia finita',
  'standup virou sentadown de 40min',
];
